import { Dimensions, StyleSheet } from 'react-native';
import { BorderRadius, BorderWidth, Spacing, Theme, Typography } from '@/constants/theme';
import { withAlpha } from '@/utils/colors';
import { rf } from '@/utils/responsive';

export const createStyles = (theme: Theme) => {
  const { width, height } = Dimensions.get('window');
  const isCompactScreen = width <= 390 || height <= 760;

  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.backgroundRoot,
    },
    topPanel: {
      marginHorizontal: isCompactScreen ? 10 : Spacing.sm,
      marginTop: isCompactScreen ? 10 : Spacing.sm,
      borderRadius: BorderRadius.xl,
      backgroundColor: theme.backgroundElevated,
      borderWidth: BorderWidth.normal,
      borderColor: theme.border,
      shadowColor: theme.shadowColor,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: theme.isDark ? 0.18 : 0.06,
      shadowRadius: 14,
      elevation: 3,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: Spacing.md,
      paddingTop: Spacing.sm,
      paddingBottom: Spacing.xs,
    },
    backButton: {
      width: 40,
      height: 40,
      borderRadius: BorderRadius.lg,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.backgroundDefault,
      borderWidth: BorderWidth.normal,
      borderColor: theme.border,
    },
    headerTitle: {
      ...Typography.title,
      color: theme.textPrimary,
      textAlign: 'center',
    },
    headerMenuButton: {
      width: 40,
      height: 40,
      borderRadius: BorderRadius.lg,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.backgroundDefault,
      borderWidth: BorderWidth.normal,
      borderColor: theme.border,
    },
    accountPanel: {
      flexDirection: 'row',
      gap: Spacing.xs,
      marginHorizontal: isCompactScreen ? 10 : Spacing.sm,
      marginTop: Spacing.sm,
      padding: 4,
      borderRadius: BorderRadius.lg,
      backgroundColor: theme.backgroundElevated,
      borderWidth: BorderWidth.normal,
      borderColor: theme.border,
    },
    accountButton: {
      flex: 1,
      minHeight: 38,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: BorderRadius.md,
      backgroundColor: 'transparent',
    },
    accountButtonActive: {
      backgroundColor: theme.primary,
      shadowColor: theme.shadowColor,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: theme.isDark ? 0.2 : 0.1,
      shadowRadius: 8,
      elevation: 2,
    },
    accountButtonText: {
      ...Typography.captionMedium,
      color: theme.textSecondary,
    },
    accountButtonTextActive: {
      color: theme.buttonPrimaryText,
      fontWeight: '800',
    },
    resultSection: {
      flex: 1,
      marginHorizontal: isCompactScreen ? 10 : Spacing.sm,
      marginTop: Spacing.sm,
      marginBottom: Spacing.sm,
      borderRadius: BorderRadius.xl,
      backgroundColor: theme.backgroundElevated,
      borderWidth: BorderWidth.normal,
      borderColor: theme.border,
      overflow: 'hidden',
    },
    queryCard: {
      minHeight: 68,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: Spacing.sm,
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.sm,
      backgroundColor: theme.backgroundDefault,
      borderBottomWidth: BorderWidth.thin,
      borderBottomColor: theme.borderLight,
    },
    queryMain: {
      flex: 1,
      minWidth: 0,
      gap: 6,
    },
    queryFieldRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.xs,
    },
    queryLabel: {
      width: 60,
      ...Typography.tiny,
      color: theme.textSecondary,
      fontWeight: '800',
    },
    queryValue: {
      flex: 1,
      ...Typography.captionMedium,
      color: theme.textPrimary,
      fontWeight: '800',
    },
    queryBadge: {
      minHeight: 28,
      paddingHorizontal: 10,
      borderRadius: BorderRadius.full,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: withAlpha(theme.primary, theme.isDark ? 0.2 : 0.12),
    },
    queryBadgeText: {
      ...Typography.captionMedium,
      color: theme.primary,
      fontWeight: '800',
    },
    errorCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.xs,
      margin: Spacing.sm,
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.sm,
      borderRadius: BorderRadius.lg,
      backgroundColor: withAlpha(theme.error, theme.isDark ? 0.18 : 0.1),
      borderWidth: BorderWidth.normal,
      borderColor: withAlpha(theme.error, theme.isDark ? 0.35 : 0.22),
    },
    errorText: {
      flex: 1,
      ...Typography.captionMedium,
      color: theme.error,
    },
    loadingCard: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      gap: Spacing.sm,
      padding: Spacing.xl,
    },
    loadingText: {
      ...Typography.captionMedium,
      color: theme.textSecondary,
    },
    list: {
      flex: 1,
    },
    listContent: {
      padding: Spacing.sm,
      gap: Spacing.sm,
    },
    listEmptyContent: {
      flexGrow: 1,
      alignItems: 'center',
      justifyContent: 'center',
      padding: Spacing.md,
    },
    stockCard: {
      minHeight: 74,
      borderRadius: BorderRadius.lg,
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.sm,
      backgroundColor: theme.backgroundDefault,
      borderWidth: BorderWidth.normal,
      borderColor: theme.border,
      shadowColor: theme.shadowColor,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: theme.isDark ? 0.16 : 0.05,
      shadowRadius: 10,
      elevation: 2,
    },
    stockCardHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: Spacing.sm,
    },
    stockTitleBlock: {
      flex: 1,
      minWidth: 0,
    },
    stockWarehouseName: {
      ...Typography.smallMedium,
      color: theme.textPrimary,
      fontWeight: '800',
    },
    stockWarehouseCode: {
      ...Typography.tiny,
      color: theme.textMuted,
      marginTop: 4,
    },
    stockQuantityBlock: {
      alignItems: 'flex-end',
      flexShrink: 0,
    },
    stockQuantity: {
      fontSize: rf(20),
      lineHeight: rf(26),
      color: theme.primary,
      fontWeight: '900',
    },
    stockQuantityLabel: {
      ...Typography.tiny,
      color: theme.textMuted,
      marginTop: 2,
    },
    empty: {
      width: '100%',
    },
  });
};
