import { StyleSheet } from 'react-native';
import { BorderRadius, BorderWidth, Spacing, Theme } from '@/constants/theme';
import { APP_MODAL_MAX_WIDTH } from '@/constants/modal';
import { withAlpha } from '@/utils/colors';

export const createStyles = (theme: Theme) => {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.backgroundRoot,
    },
    scrollContent: {
      padding: Spacing.md,
      paddingBottom: 100,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: Spacing.md,
      padding: Spacing.lg,
      borderRadius: BorderRadius['2xl'],
      backgroundColor: theme.backgroundElevated,
      borderWidth: BorderWidth.normal,
      borderColor: theme.border,
      shadowColor: theme.shadowColor,
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: theme.isDark ? 0.2 : 0.08,
      shadowRadius: 18,
      elevation: 4,
    },
    backButton: {
      width: 44,
      height: 44,
      borderRadius: BorderRadius.lg,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: theme.backgroundTertiary,
      marginRight: Spacing.sm,
    },
    headerContent: {
      flex: 1,
    },
    title: {
      fontSize: 20,
      fontWeight: '800',
      color: theme.textPrimary,
      letterSpacing: -0.5,
    },
    subtitle: {
      marginTop: 4,
      fontSize: 12,
      lineHeight: 18,
      color: theme.textSecondary,
    },
    toolbar: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: Spacing.sm,
      marginBottom: Spacing.sm,
    },
    toolbarTextBlock: {
      flex: 1,
    },
    toolbarTitle: {
      fontSize: 14,
      fontWeight: '700',
      color: theme.textPrimary,
    },
    toolbarSubtitle: {
      marginTop: 2,
      fontSize: 12,
      color: theme.textSecondary,
    },
    addButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.sm,
      borderRadius: BorderRadius.lg,
      backgroundColor: theme.primary,
    },
    addButtonText: {
      fontSize: 13,
      fontWeight: '700',
      color: theme.buttonPrimaryText,
    },
    emptyContainer: {
      paddingVertical: Spacing['4xl'],
    },
    fieldItem: {
      padding: Spacing.md,
      borderRadius: BorderRadius.xl,
      backgroundColor: theme.backgroundElevated,
      borderWidth: BorderWidth.normal,
      borderColor: theme.border,
      marginBottom: Spacing.sm,
      shadowColor: theme.shadowColor,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: theme.isDark ? 0.18 : 0.05,
      shadowRadius: 12,
      elevation: 2,
    },
    fieldMainRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: Spacing.sm,
    },
    fieldLeft: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: Spacing.sm,
    },
    orderBadge: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: withAlpha(theme.primary, 0.1),
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 1,
    },
    orderBadgeText: {
      fontSize: 12,
      fontWeight: '700',
      color: theme.primary,
    },
    fieldTextBlock: {
      flex: 1,
    },
    fieldName: {
      fontSize: 14,
      fontWeight: '700',
      color: theme.textPrimary,
    },
    metaRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
      gap: Spacing.xs,
      marginTop: 6,
    },
    typeChip: {
      fontSize: 11,
      fontWeight: '700',
      color: theme.textPrimary,
      backgroundColor: theme.backgroundTertiary,
      paddingHorizontal: Spacing.sm,
      paddingVertical: 4,
      borderRadius: BorderRadius.md,
    },
    requiredChip: {
      fontSize: 11,
      fontWeight: '700',
      color: theme.error,
      backgroundColor: withAlpha(theme.error, 0.1),
      paddingHorizontal: Spacing.sm,
      paddingVertical: 4,
      borderRadius: BorderRadius.md,
    },
    metaText: {
      fontSize: 11,
      color: theme.textSecondary,
    },
    actionRow: {
      flexDirection: 'row',
      gap: Spacing.xs,
    },
    iconButton: {
      width: 34,
      height: 34,
      borderRadius: BorderRadius.lg,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: theme.backgroundTertiary,
      borderWidth: BorderWidth.normal,
      borderColor: theme.border,
    },
    optionsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: Spacing.xs,
      marginTop: Spacing.sm,
      marginLeft: 36,
    },
    optionTag: {
      fontSize: 11,
      color: theme.textSecondary,
      backgroundColor: theme.backgroundTertiary,
      paddingHorizontal: Spacing.sm,
      paddingVertical: 4,
      borderRadius: BorderRadius.md,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: theme.overlay,
      justifyContent: 'center',
      alignItems: 'center',
      padding: Spacing.md,
    },
    modalContent: {
      width: '100%',
      maxWidth: APP_MODAL_MAX_WIDTH,
    },
    modalHeaderSection: {
      paddingHorizontal: Spacing.md,
      paddingTop: Spacing.md,
    },
    modalBodySection: {
      flex: 1,
      paddingHorizontal: 0,
      paddingBottom: 0,
      alignItems: 'stretch',
    },
    modalFormScroll: {
      alignSelf: 'stretch',
      width: '100%',
    },
    modalFormScrollContent: {
      width: '100%',
      alignSelf: 'stretch',
      paddingHorizontal: Spacing.md,
      paddingBottom: Spacing.sm,
    },
    formGroup: {
      marginBottom: Spacing.md,
    },
    formLabel: {
      marginBottom: Spacing.xs,
      fontSize: 13,
      fontWeight: '600',
      color: theme.textPrimary,
    },
    formInput: {
      width: '100%',
      alignSelf: 'stretch',
      minHeight: 46,
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.sm + 1,
      borderRadius: BorderRadius.lg,
      backgroundColor: theme.backgroundTertiary,
      borderWidth: BorderWidth.normal,
      borderColor: theme.border,
      fontSize: 14,
      color: theme.textPrimary,
      textAlignVertical: 'center',
    },
    optionsInput: {
      height: 82,
      maxHeight: 82,
      textAlignVertical: 'top',
    },
    typeSelector: {
      flexDirection: 'row',
      gap: Spacing.xs,
      padding: 4,
      borderRadius: BorderRadius.xl,
      backgroundColor: theme.backgroundTertiary,
      borderWidth: BorderWidth.normal,
      borderColor: theme.border,
    },
    typeButton: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      minHeight: 42,
      paddingHorizontal: Spacing.sm,
      paddingVertical: Spacing.sm - 1,
      borderRadius: BorderRadius.lg,
      backgroundColor: 'transparent',
      borderWidth: 0,
    },
    typeButtonActive: {
      backgroundColor: theme.backgroundElevated,
      borderWidth: BorderWidth.normal,
      borderColor: withAlpha(theme.primary, 0.26),
    },
    typeButtonText: {
      fontSize: 13,
      fontWeight: '600',
      color: theme.textPrimary,
    },
    typeButtonTextActive: {
      color: theme.primary,
      fontWeight: '700',
    },
    typeHint: {
      marginTop: Spacing.xs,
      fontSize: 11,
      lineHeight: 16,
      color: theme.textSecondary,
    },
    optionsHint: {
      marginBottom: Spacing.xs,
      fontSize: 11,
      lineHeight: 16,
      color: theme.textMuted,
    },
    requiredRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: Spacing.sm,
      padding: Spacing.md,
      borderRadius: BorderRadius.xl,
      backgroundColor: theme.backgroundTertiary,
      borderWidth: BorderWidth.normal,
      borderColor: theme.border,
    },
    checkbox: {
      width: 20,
      height: 20,
      borderRadius: 6,
      borderWidth: 2,
      borderColor: theme.border,
      justifyContent: 'center',
      alignItems: 'center',
    },
    checkboxChecked: {
      backgroundColor: theme.primary,
      borderColor: theme.primary,
    },
    requiredTextBlock: {
      flex: 1,
      paddingTop: 1,
    },
    requiredTitle: {
      fontSize: 13,
      fontWeight: '700',
      color: theme.textPrimary,
    },
    requiredSubtitle: {
      marginTop: 2,
      fontSize: 11,
      color: theme.textSecondary,
    },
    modalFooter: {
      paddingHorizontal: Spacing.md,
      paddingBottom: Spacing.md,
      paddingTop: Spacing.sm,
      borderTopWidth: BorderWidth.normal,
      borderTopColor: theme.border,
      backgroundColor: withAlpha(theme.backgroundTertiary, theme.isDark ? 0.26 : 0.42),
    },
    modalActions: {
      marginTop: 0,
    },
  });
};
