import { StyleSheet } from 'react-native';
import { BorderRadius, BorderWidth, Spacing, Theme, Typography } from '@/constants/theme';
import { APP_MODAL_MAX_WIDTH } from '@/constants/modal';
import { withAlpha } from '@/utils/colors';
import { rf } from '@/utils/responsive';

export const createStyles = (theme: Theme) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.backgroundRoot,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
      paddingHorizontal: Spacing.md,
      paddingBottom: Spacing.sm,
    },
    backButton: {
      width: 42,
      height: 42,
      borderRadius: BorderRadius.lg,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: theme.backgroundElevated,
      borderWidth: BorderWidth.normal,
      borderColor: theme.border,
    },
    headerTextBlock: {
      flex: 1,
      minWidth: 0,
    },
    title: {
      ...Typography.h4,
      color: theme.textPrimary,
      letterSpacing: -0.2,
    },
    subtitle: {
      ...Typography.caption,
      color: theme.textSecondary,
      marginTop: 2,
    },
    filterCard: {
      marginHorizontal: Spacing.md,
      marginBottom: Spacing.sm,
      padding: Spacing.md,
      borderRadius: BorderRadius['2xl'],
      borderWidth: BorderWidth.normal,
      borderColor: theme.border,
      backgroundColor: theme.backgroundElevated,
      shadowColor: theme.shadowColor,
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: theme.isDark ? 0.18 : 0.06,
      shadowRadius: 16,
      elevation: 3,
    },
    filterTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: Spacing.md,
      marginBottom: Spacing.sm,
    },
    warehouseSelectButton: {
      flex: 1,
      minWidth: 0,
      minHeight: 48,
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
      paddingHorizontal: Spacing.sm,
      paddingVertical: Spacing.xs,
      borderRadius: BorderRadius.xl,
      backgroundColor: theme.backgroundTertiary,
      borderWidth: BorderWidth.normal,
      borderColor: theme.borderLight,
    },
    warehouseIconBox: {
      width: 32,
      height: 32,
      borderRadius: BorderRadius.md,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: withAlpha(theme.primary, theme.isDark ? 0.18 : 0.1),
    },
    warehouseSelectTextBlock: {
      flex: 1,
      minWidth: 0,
    },
    filterLabel: {
      ...Typography.caption,
      color: theme.textMuted,
      marginBottom: 2,
    },
    filterTitle: {
      ...Typography.title,
      color: theme.textPrimary,
    },
    filterSummary: {
      minWidth: 60,
      alignItems: 'center',
      paddingHorizontal: Spacing.sm,
      paddingVertical: 6,
      borderRadius: BorderRadius.lg,
      backgroundColor: withAlpha(theme.primary, theme.isDark ? 0.18 : 0.08),
      borderWidth: BorderWidth.normal,
      borderColor: withAlpha(theme.primary, theme.isDark ? 0.28 : 0.14),
    },
    filterSummaryValue: {
      ...Typography.bodyMedium,
      fontWeight: '800',
      color: theme.primary,
    },
    filterSummaryLabel: {
      ...Typography.tiny,
      color: theme.textSecondary,
    },
    totalRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingTop: Spacing.sm,
      marginTop: Spacing.xs,
      borderTopWidth: BorderWidth.thin,
      borderTopColor: theme.borderLight,
    },
    totalText: {
      ...Typography.captionMedium,
      color: theme.textSecondary,
    },
    listContent: {
      paddingHorizontal: Spacing.md,
      paddingTop: Spacing.xs,
      gap: Spacing.sm,
    },
    emptyListContent: {
      flexGrow: 1,
      justifyContent: 'center',
    },
    documentCard: {
      padding: Spacing.sm,
      borderRadius: BorderRadius['2xl'],
      borderWidth: BorderWidth.normal,
      borderColor: theme.border,
      backgroundColor: theme.backgroundElevated,
      shadowColor: theme.shadowColor,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: theme.isDark ? 0.16 : 0.05,
      shadowRadius: 14,
      elevation: 2,
    },
    documentHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
    },
    documentIcon: {
      width: 34,
      height: 34,
      borderRadius: BorderRadius.lg,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: withAlpha(theme.primary, theme.isDark ? 0.18 : 0.1),
      borderWidth: BorderWidth.normal,
      borderColor: withAlpha(theme.primary, theme.isDark ? 0.28 : 0.14),
    },
    documentTitleBlock: {
      flex: 1,
      minWidth: 0,
    },
    documentTitleRow: {
      minHeight: 28,
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.xs,
    },
    documentNo: {
      ...Typography.bodyMedium,
      flex: 1,
      minWidth: 0,
      fontWeight: '800',
      color: theme.textPrimary,
    },
    syncInlineButton: {
      minHeight: 26,
      minWidth: 70,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 4,
      paddingHorizontal: Spacing.xs,
      borderRadius: BorderRadius.full,
      borderWidth: BorderWidth.normal,
    },
    syncInlineButtonDisabled: {
      opacity: 0.72,
    },
    syncInlineText: {
      ...Typography.tiny,
      fontWeight: '900',
    },
    documentMeta: {
      ...Typography.caption,
      color: theme.textSecondary,
      marginTop: 2,
    },
    statsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: Spacing.sm,
      paddingVertical: 6,
      borderRadius: BorderRadius.xl,
      backgroundColor: theme.backgroundTertiary,
    },
    statItem: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: 36,
    },
    statValue: {
      fontSize: rf(15),
      lineHeight: rf(21),
      fontWeight: '800',
      color: theme.textPrimary,
    },
    statLabel: {
      ...Typography.tiny,
      color: theme.textSecondary,
      marginTop: 1,
    },
    statDivider: {
      width: BorderWidth.thin,
      height: 24,
      backgroundColor: theme.border,
    },
    detailWrap: {
      marginTop: Spacing.sm,
      gap: Spacing.xs,
      paddingTop: Spacing.xs,
      borderTopWidth: BorderWidth.thin,
      borderTopColor: theme.borderLight,
    },
    detailHintRow: {
      minHeight: 22,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 2,
    },
    detailHint: {
      ...Typography.caption,
      color: theme.textMuted,
    },
    detailGroupCard: {
      overflow: 'hidden',
      borderRadius: BorderRadius.xl,
      backgroundColor: theme.backgroundRoot,
      borderWidth: BorderWidth.normal,
      borderColor: theme.borderLight,
    },
    detailGroupRow: {
      minHeight: 58,
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
      paddingHorizontal: Spacing.sm,
      paddingVertical: Spacing.sm,
    },
    detailGroupContent: {
      flex: 1,
      minWidth: 0,
    },
    detailGroupTitle: {
      ...Typography.captionMedium,
      fontWeight: '900',
      color: theme.textPrimary,
    },
    detailGroupMeta: {
      ...Typography.tiny,
      color: theme.textSecondary,
      marginTop: 2,
    },
    detailGroupRight: {
      minWidth: 58,
      alignItems: 'flex-end',
    },
    detailGroupQuantityRow: {
      flexDirection: 'row',
      alignItems: 'baseline',
      gap: 3,
    },
    detailGroupCount: {
      ...Typography.tiny,
      fontWeight: '800',
      color: theme.textMuted,
      marginTop: 2,
    },
    detailGroupQty: {
      ...Typography.captionMedium,
      fontWeight: '900',
      color: theme.primary,
    },
    detailGroupDetails: {
      gap: Spacing.xs,
      paddingHorizontal: Spacing.xs,
      paddingBottom: Spacing.xs,
      borderTopWidth: BorderWidth.thin,
      borderTopColor: theme.borderLight,
      backgroundColor: theme.backgroundTertiary,
    },
    detailRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
      padding: Spacing.sm,
      borderRadius: BorderRadius.xl,
      backgroundColor: theme.backgroundRoot,
      borderWidth: BorderWidth.normal,
      borderColor: theme.borderLight,
    },
    detailIndex: {
      width: 26,
      height: 26,
      borderRadius: BorderRadius.full,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: withAlpha(theme.primary, theme.isDark ? 0.18 : 0.08),
    },
    detailIndexText: {
      ...Typography.tiny,
      fontWeight: '800',
      color: theme.primary,
    },
    detailContent: {
      flex: 1,
      minWidth: 0,
    },
    detailTitle: {
      ...Typography.captionMedium,
      color: theme.textPrimary,
      fontWeight: '800',
    },
    detailMeta: {
      ...Typography.tiny,
      color: theme.textSecondary,
      marginTop: 1,
    },
    detailQtyBox: {
      minWidth: 54,
      alignItems: 'flex-end',
    },
    detailQuantityRow: {
      flexDirection: 'row',
      alignItems: 'baseline',
      gap: 3,
    },
    detailQty: {
      ...Typography.captionMedium,
      fontWeight: '900',
      color: theme.primary,
    },
    detailQtyUnit: {
      ...Typography.captionMedium,
      fontWeight: '900',
      color: theme.primary,
    },
    pickerOverlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      justifyContent: 'center',
      alignItems: 'center',
      padding: Spacing.xl,
      backgroundColor: theme.overlay,
      zIndex: 100,
    },
    pickerBox: {
      width: '100%',
      maxWidth: APP_MODAL_MAX_WIDTH,
      maxHeight: '70%',
      padding: Spacing.md,
      borderRadius: BorderRadius['2xl'],
      backgroundColor: theme.backgroundElevated,
      borderWidth: BorderWidth.normal,
      borderColor: theme.border,
      shadowColor: theme.shadowColor,
      shadowOffset: { width: 0, height: 16 },
      shadowOpacity: theme.isDark ? 0.28 : 0.12,
      shadowRadius: 24,
      elevation: 10,
    },
    pickerTitle: {
      ...Typography.title,
      color: theme.textPrimary,
      textAlign: 'center',
      marginBottom: Spacing.sm,
    },
    pickerList: {
      gap: 4,
      paddingVertical: 2,
    },
    pickerItem: {
      minHeight: 46,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: Spacing.sm,
      paddingHorizontal: Spacing.sm,
      paddingVertical: Spacing.sm,
      borderRadius: BorderRadius.lg,
    },
    pickerItemActive: {
      backgroundColor: withAlpha(theme.primary, theme.isDark ? 0.18 : 0.08),
    },
    pickerItemLeft: {
      flex: 1,
      minWidth: 0,
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
    },
    pickerItemText: {
      ...Typography.smallMedium,
      flex: 1,
      color: theme.textPrimary,
    },
    pickerItemTextActive: {
      color: theme.primary,
      fontWeight: '800',
    },
    pickerClose: {
      minHeight: 46,
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: Spacing.sm,
      borderRadius: BorderRadius.lg,
      backgroundColor: theme.backgroundTertiary,
      borderWidth: BorderWidth.normal,
      borderColor: theme.border,
    },
    pickerCloseText: {
      ...Typography.bodyMedium,
      fontWeight: '700',
      color: theme.textPrimary,
    },
  });
