import { StyleSheet } from 'react-native';
import { Spacing, Typography, type Theme } from '@/constants/theme';

export const createStyles = (theme: Theme) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: theme.backgroundRoot },
    scrollContent: { padding: Spacing.md },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 8,
      gap: 8,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.border,
    },
    backButton: { width: 44, height: 44, justifyContent: 'center', alignItems: 'center' },
    headerContent: { flex: 1 },
    title: { ...Typography.title, letterSpacing: 0, color: theme.textPrimary },
    headerAction: {
      minHeight: 44,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 12,
    },
    headerActionText: { ...Typography.smallMedium, color: theme.textSecondary },
    sortHint: { ...Typography.caption, color: theme.textSecondary, marginTop: 2 },
    addButton: {
      minHeight: 44,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      backgroundColor: theme.primary,
      paddingHorizontal: 12,
      borderRadius: 8,
    },
    addButtonText: { ...Typography.smallMedium, color: theme.buttonPrimaryText },
    emptyContainer: { alignItems: 'center', paddingVertical: 48, paddingHorizontal: 24 },
    ruleItem: {
      backgroundColor: theme.backgroundElevated,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: theme.border,
      padding: 14,
      flexDirection: 'row',
      alignItems: 'center',
      minHeight: 80,
    },
    swipeContainer: { borderRadius: 8, overflow: 'hidden' },
    ruleContent: { flex: 1, minWidth: 0, gap: 4 },
    ruleSwitch: { marginLeft: 8, justifyContent: 'center' },
    ruleItemDragging: {
      elevation: 10,
      shadowColor: '#000000',
      shadowOpacity: 0.28,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 6 },
      borderColor: theme.primary,
    },
    ruleItemDimmed: { opacity: 0.78 },
    dragHandle: {
      marginLeft: 8,
      width: 36,
      minHeight: 44,
      justifyContent: 'center',
      alignItems: 'center',
    },
    deleteAction: {
      width: 88,
      backgroundColor: theme.error,
      justifyContent: 'center',
      alignItems: 'center',
    },
    deleteActionText: { ...Typography.smallMedium, color: theme.buttonPrimaryText, marginTop: 4 },
    ruleName: { ...Typography.smallMedium, color: theme.textPrimary },
    ruleSeparator: { ...Typography.caption, color: theme.textSecondary },
    ruleFields: { ...Typography.caption, color: theme.textMuted },
    ruleEditorScreen: {
      flex: 1,
      width: '100%',
      maxWidth: 720,
      alignSelf: 'center',
      backgroundColor: theme.backgroundRoot,
    },
    ruleEditorHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      paddingHorizontal: 16,
      paddingTop: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.border,
    },
    ruleEditorBody: { flex: 1 },
    ruleEditorBodyContent: { paddingHorizontal: 16 },
    ruleEditorFooter: {
      paddingHorizontal: 16,
      paddingTop: 12,
      backgroundColor: theme.backgroundRoot,
      borderTopWidth: 1,
      borderTopColor: theme.border,
    },
    ruleEditorActions: { marginTop: 0 },
    doneButton: {
      minHeight: 48,
      borderRadius: 8,
      backgroundColor: theme.primary,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    inputLabel: {
      ...Typography.smallMedium,
      color: theme.textPrimary,
      marginBottom: 8,
      marginTop: 16,
    },
    textInput: {
      ...Typography.small,
      color: theme.textPrimary,
      minHeight: 48,
      paddingVertical: 12,
      paddingHorizontal: 12,
      backgroundColor: theme.backgroundDefault,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: theme.border,
    },
    invalidInput: { borderColor: theme.error },
    validationText: { color: theme.error },
    validationMessage: { ...Typography.caption, marginTop: 6 },
    sectionTitle: {
      ...Typography.smallMedium,
      color: theme.textSecondary,
      marginTop: 24,
      marginBottom: 4,
    },
    settingsRow: {
      minHeight: 72,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingVertical: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.border,
    },
    settingsTitle: { ...Typography.smallMedium, color: theme.textPrimary },
    settingsValue: { ...Typography.caption, color: theme.textSecondary },
    prefixRow: { paddingBottom: 8 },
    separatorOptions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    separatorBtn: {
      minWidth: 48,
      minHeight: 44,
      paddingHorizontal: 12,
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 8,
      backgroundColor: theme.backgroundDefault,
      borderWidth: 1,
      borderColor: theme.border,
    },
    separatorBtnActive: { backgroundColor: theme.primary, borderColor: theme.primary },
    separatorBtnText: { ...Typography.smallMedium, color: theme.textPrimary },
    separatorBtnTextActive: { color: theme.buttonPrimaryText },
    terminatorSection: {
      marginTop: 24,
      paddingTop: 16,
      borderTopWidth: 1,
      borderColor: theme.border,
      gap: 12,
    },
    terminatorTitle: { ...Typography.smallMedium, color: theme.textPrimary },
    terminatorDetails: { gap: 8, paddingTop: 8 },
    terminatorLabel: { ...Typography.caption, color: theme.textSecondary },
    fieldOptions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    fieldBtn: {
      minHeight: 44,
      justifyContent: 'center',
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 8,
      backgroundColor: theme.backgroundDefault,
      borderWidth: 1,
      borderColor: theme.border,
    },
    fieldBtnActive: { backgroundColor: theme.primary, borderColor: theme.primary },
    fieldBtnText: { ...Typography.small, color: theme.textPrimary },
    fieldBtnTextActive: { color: theme.buttonPrimaryText },
    selectedFieldsContainer: { marginTop: 24 },
    selectedFieldsLabel: { ...Typography.smallMedium, color: theme.textPrimary, marginBottom: 8 },
    selectedFieldItem: {
      flexDirection: 'row',
      alignItems: 'center',
      minHeight: 52,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.border,
    },
    selectedFieldIndex: { ...Typography.caption, color: theme.textMuted, width: 24 },
    selectedFieldName: { ...Typography.small, color: theme.textPrimary, flex: 1 },
    selectedFieldActions: { flexDirection: 'row' },
    fieldAction: { minWidth: 44, minHeight: 44, alignItems: 'center', justifyContent: 'center' },
    ignoreButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      minHeight: 44,
      marginTop: 8,
    },
    sectionContainer: { paddingBottom: 16 },
    conditionsList: { marginVertical: 16 },
    conditionItem: {
      flexDirection: 'row',
      alignItems: 'center',
      borderBottomWidth: 1,
      borderColor: theme.border,
      minHeight: 52,
    },
    conditionText: { ...Typography.small, color: theme.textPrimary, flex: 1 },
    addConditionContainer: { marginTop: 8 },
    conditionInputRow: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.backgroundDefault,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: theme.border,
      paddingHorizontal: 12,
      minHeight: 52,
      marginBottom: 12,
      gap: 8,
    },
    inputRowLabel: { ...Typography.caption, color: theme.textSecondary, flexShrink: 0 },
    inputRowField: {
      ...Typography.small,
      flex: 1,
      minWidth: 0,
      color: theme.textPrimary,
      paddingVertical: 12,
    },
    conditionLabel: { ...Typography.caption, color: theme.textSecondary },
    fieldSelectBtn: {
      minHeight: 44,
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
      minWidth: 0,
    },
    fieldSelectText: { ...Typography.small, color: theme.textPrimary, flexShrink: 1 },
    conditionKeywordInput: {
      ...Typography.small,
      flex: 1,
      minWidth: 0,
      color: theme.textPrimary,
      paddingVertical: 12,
    },
    addConditionBtn: {
      width: 44,
      height: 44,
      backgroundColor: theme.primary,
      borderRadius: 8,
      justifyContent: 'center',
      alignItems: 'center',
    },
    noFieldsHint: { ...Typography.caption, color: theme.textMuted, marginTop: 16 },
  });
