import { StyleSheet } from 'react-native';
import { BorderRadius, BorderWidth, Spacing, Theme, Typography } from '@/constants/theme';
import { withAlpha } from '@/utils/colors';

export const createStyles = (theme: Theme) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: theme.backgroundRoot },
    topPanel: {
      marginHorizontal: Spacing.sm,
      marginTop: Spacing.sm,
      borderRadius: BorderRadius.xl,
      backgroundColor: theme.backgroundElevated,
      borderWidth: BorderWidth.normal,
      borderColor: theme.border,
      overflow: 'hidden',
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: Spacing.md,
      paddingTop: Spacing.sm,
      paddingBottom: Spacing.xs,
    },
    headerButton: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: BorderRadius.lg,
      backgroundColor: theme.backgroundDefault,
      borderWidth: BorderWidth.normal,
      borderColor: theme.border,
    },
    headerTitle: { ...Typography.title, color: theme.textPrimary, textAlign: 'center' },
    accountPanel: {
      flexDirection: 'row',
      gap: Spacing.xs,
      marginHorizontal: Spacing.sm,
      marginTop: Spacing.sm,
      padding: 4,
      borderRadius: BorderRadius.lg,
      backgroundColor: theme.backgroundElevated,
      borderWidth: BorderWidth.normal,
      borderColor: theme.border,
    },
    accountButton: {
      flex: 1,
      minHeight: 38,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: BorderRadius.md,
    },
    accountButtonActive: { backgroundColor: theme.primary },
    accountButtonText: { ...Typography.captionMedium, color: theme.textSecondary },
    accountButtonTextActive: { color: theme.buttonPrimaryText, fontWeight: '800' },
    manualLookupBar: {
      minHeight: 48,
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.xs,
      marginHorizontal: Spacing.sm,
      marginTop: Spacing.sm,
      paddingLeft: Spacing.md,
      paddingRight: 4,
      paddingVertical: 4,
      borderRadius: BorderRadius.lg,
      backgroundColor: theme.backgroundElevated,
      borderWidth: BorderWidth.normal,
      borderColor: theme.border,
    },
    manualLookupInput: {
      flex: 1,
      minWidth: 0,
      ...Typography.smallMedium,
      color: theme.textPrimary,
      paddingVertical: Spacing.xs,
    },
    manualLookupButton: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: BorderRadius.md,
      backgroundColor: theme.primary,
    },
    errorCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.xs,
      marginHorizontal: Spacing.sm,
      marginTop: Spacing.sm,
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.sm,
      borderRadius: BorderRadius.lg,
      backgroundColor: withAlpha(theme.error, theme.isDark ? 0.18 : 0.1),
      borderWidth: BorderWidth.normal,
      borderColor: withAlpha(theme.error, theme.isDark ? 0.35 : 0.22),
    },
    errorText: { flex: 1, ...Typography.captionMedium, color: theme.error },
    listSection: {
      flex: 1,
      margin: Spacing.sm,
      borderRadius: BorderRadius.xl,
      backgroundColor: theme.backgroundElevated,
      borderWidth: BorderWidth.normal,
      borderColor: theme.border,
      overflow: 'hidden',
    },
    listHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.sm,
      borderBottomWidth: BorderWidth.thin,
      borderBottomColor: theme.borderLight,
    },
    listTitle: { ...Typography.captionMedium, color: theme.textSecondary },
    listCount: { ...Typography.captionMedium, color: theme.primary, fontWeight: '800' },
    list: { flex: 1 },
    listContent: { padding: Spacing.sm, gap: Spacing.sm },
    listEmptyContent: { flexGrow: 1, justifyContent: 'center', padding: Spacing.md },
    empty: { width: '100%' },
    loadingState: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: Spacing.sm },
    loadingText: { ...Typography.captionMedium, color: theme.textSecondary },
    voucherCard: {
      borderRadius: BorderRadius.lg,
      backgroundColor: theme.backgroundDefault,
      borderWidth: BorderWidth.normal,
      borderColor: theme.border,
      overflow: 'hidden',
    },
    voucherCardCompleted: {
      borderColor: withAlpha(theme.success, theme.isDark ? 0.45 : 0.3),
      backgroundColor: withAlpha(theme.success, theme.isDark ? 0.08 : 0.04),
    },
    voucherHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.sm,
    },
    voucherMain: { flex: 1, minWidth: 0 },
    voucherTitleRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.xs },
    voucherCode: { flex: 1, ...Typography.smallMedium, color: theme.textPrimary, fontWeight: '800' },
    pendingBadge: {
      minHeight: 24,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 8,
      borderRadius: BorderRadius.full,
      backgroundColor: withAlpha(theme.warning, theme.isDark ? 0.2 : 0.12),
    },
    pendingBadgeText: { ...Typography.tiny, color: theme.warning, fontWeight: '800' },
    completedBadge: {
      backgroundColor: withAlpha(theme.success, theme.isDark ? 0.2 : 0.12),
    },
    completedBadgeText: { color: theme.success },
    partnerName: { ...Typography.captionMedium, color: theme.textSecondary, marginTop: 4 },
    voucherMeta: { ...Typography.tiny, color: theme.textMuted, marginTop: 3 },
    completedNotice: {
      minHeight: 38,
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.xs,
      paddingHorizontal: Spacing.md,
      paddingVertical: Spacing.xs,
      borderTopWidth: BorderWidth.thin,
      borderTopColor: withAlpha(theme.success, theme.isDark ? 0.28 : 0.18),
    },
    completedNoticeText: {
      flex: 1,
      ...Typography.captionMedium,
      color: theme.success,
    },
    detailSection: {
      borderTopWidth: BorderWidth.thin,
      borderTopColor: theme.borderLight,
      backgroundColor: theme.backgroundTertiary,
      padding: Spacing.sm,
      gap: Spacing.xs,
    },
    detailLoading: { minHeight: 80, alignItems: 'center', justifyContent: 'center', gap: Spacing.xs },
    detailLoadingText: { ...Typography.caption, color: theme.textMuted },
    lineRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
      paddingVertical: Spacing.sm,
      paddingHorizontal: Spacing.xs,
      borderBottomWidth: BorderWidth.thin,
      borderBottomColor: theme.borderLight,
    },
    lineMain: { flex: 1, minWidth: 0 },
    lineSpecification: { ...Typography.captionMedium, color: theme.textPrimary },
    lineCode: { ...Typography.tiny, color: theme.textMuted, marginTop: 3 },
    lineQuantityBlock: { alignItems: 'flex-end', flexShrink: 0 },
    lineQuantity: { ...Typography.smallMedium, color: theme.primary, fontWeight: '900' },
    lineUnit: { ...Typography.tiny, color: theme.textMuted, marginTop: 2 },
    startButton: {
      minHeight: 46,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: Spacing.xs,
      marginTop: Spacing.xs,
      borderRadius: BorderRadius.lg,
      backgroundColor: theme.primary,
    },
    startButtonText: { ...Typography.smallMedium, color: theme.buttonPrimaryText, fontWeight: '800' },
  });
